clear all;
f=10;
t=0:0.01:1;
X1=sin(2*pi*f*t);
X2=cos(2*pi*f*t);
subplot(3,1,1);
plot(t,X1);
xlabel('time');
ylabel('X1');
title('Sine Wave');
subplot(3,1,2);
plot(t,X2);
xlabel('time');
ylabel('X2');
title('Cosine Wave');
subplot(3,1,3);
plot(t,X1,t,X2);
xlabel('time');
ylabel('X1 and X2');
title('Sine and Cosine combined');